# SPDX-FileCopyrightText: 2025-2026 CocoIndex (upstream)
# SPDX-FileCopyrightText: 2026 Knitli Inc. (ReCoco)
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
# SPDX-FileContributor: CocoIndex Contributors
#
# SPDX-License-Identifier: Apache-2.0

[build]
# This is required by tokio-console: https://docs.rs/tokio-console/latest/tokio_console
rustflags = ["--cfg", "tokio_unstable"]
